terraform-ibm-modules/terraform-ibm-secrets-manager

- solutions/standard/catalogValidationValues.json.template
Add missing var to `catalogValidationValues.json.template`
```
/run pipeline
```
> Add missing var to catalogValidationValues.json.template

- cra-config.yaml
- ibm_catalog.json
Update to DA to fscloud profile 1.6.0
```
/run pipeline
```
> Update to DA to fscloud profile 1.6.0

- solutions/standard/main.tf
- solutions/standard/variables.tf
- tests/pr_test.go
Ref: #74 
Clarify KMS properties under standard solution
```
/run pipeline
```
> fix: clarify KMS encryption in solution

- solutions/standard/main.tf
- solutions/standard/variables.tf
Update variable to full service name
```
existing_en_instance_crn -> existing_event_notification_instance_crn
existing_sm_kms_key_crn -> existing_secrets_manager_kms_key_crn
skip_en_iam_authorization_policy -> skip_event_notification_iam_authorization_policy
```
Issue:https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/issues/73
```
/run pipeline
```
- Include …
> feat:full service name in variables

- cra-config.yaml
- ibm_catalog.json
- solutions/standard/catalogValidationValues.json.template
- solutions/standard/main.tf
- solutions/standard/provider.tf
- solutions/standard/variables.tf
- tests/pr_test.go
Issue:
https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/issues/75
https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/issues/79
```
/run pipeline
```
> feat: group input variables inside ibm_catalog for DA

- tests/existing-resources/Readme.md
- tests/existing-resources/main.tf
- tests/existing-resources/outputs.tf
- tests/existing-resources/provider.tf
- tests/existing-resources/variables.tf
- tests/existing-resources/version.tf
- tests/pr_test.go
> test: add a new test for DA using existing resources

- solutions/standard/README.md
- solutions/standard/main.tf
- solutions/standard/outputs.tf
- solutions/standard/variables.tf
- tests/existing-resources/main.tf
- tests/existing-resources/outputs.tf
- tests/other_test.go
- tests/pr_test.go
Issue: https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/issues/107
```
/run pipeline
```
> feat: add support to use existing SM instance for DA

- solutions/standard/main.tf
- solutions/standard/outputs.tf
- tests/pr_test.go
> fix: do not create kms key if existing SM instance is passed

- solutions/standard/main.tf
- solutions/standard/outputs.tf
- solutions/standard/variables.tf
> fix: fix kms reference error when sm crn is set

- examples/complete/README.md
- examples/complete/main.tf
- solutions/standard/main.tf
- tests/existing-resources/main.tf
> fix: bump kms-all-inclusive

- solutions/standard/main.tf
- solutions/standard/variables.tf
- tests/pr_test.go
- updated DA variable allowed_network to default to 'private-only' since all UI features are now avaiable for4 private only instances:
- added new variable `existing_secrets_endpoint_type` (see https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/issues/122)
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. …
> updated DA variable allowed_network to 'private-only' + added new var `existing_secrets_endpoint_type`

- examples/complete/main.tf
Add in the force delete options for key protect in the complete example
```
/run pipeline
```
> test: add force delete to created key ring/key

- solutions/standard/main.tf
> add link to provider issue as code comment

- main.tf
- tests/pr_test.go
Fix for https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/issues/172
```
/run pipeline
```
> fix: fixed bug in validation when passing existing SM instance

- cra-config.yaml
- examples/complete/README.md
- examples/complete/main.tf
- solutions/standard/main.tf
- tests/existing-resources/main.tf
The KMS bump requires a variable change. The properties passed previously required a GUID and now requires a CRN
```
/run pipeline
```
> fix(deps): update terraform-ibm-kms to 4.15.3

- solutions/standard/main.tf
| [terraform-ibm-modules/secrets-manager-iam-engine/ibm](https://registry.terraform.io/modules/terraform-ibm-modules/secrets-manager-iam-engine/ibm) ([source](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager-iam-engine)) | module | patch | `1.2.2` -> `1.2.3` |
<details>
<summary>terraform-ibm-modules/terraform-ibm-secrets-manager-iam-engine (terraform-ibm-modules/secrets-manager-iam-engine/ibm)</summary>
[Compare Source](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager-iam-engine/compare/v1.2.2...v1.2.3)
-   **deps:** update terraform-module
</details>
Run the CI pipeline when the PR is ready for review and you …
> fix: upgraded version of secrets-manager-iam-engine to 1.2.3 to fix plan issue

- solutions/standard/catalogValidationValues.json.template
- tests/other_test.go
- tests/pr_test.go
> test: use us-east HPCS

- tests/other_test.go
Basic test was not using the region selector, causing it to occasionally go to eu-es and fail due to the trial instance quota.
Github issue: https://github.ibm.com/GoldenEye/issues/issues/11389
```
/run pipeline
```
- Use the **Squash and …
> ci: fix basic test

- ibm_catalog.json
code cleanup and set on_by_default for the dependancies
```
/run pipeline
```
> fix: code cleanup and set on_by_default

- tests/other_test.go
This has caused persistent failures whenever other_tests get run. The timelines didn't match because the SM pipeline wasn't sending alerts for the first few months.
```
/run pipeline
```
> ci: include secrets module in fscloud test

- ibm_catalog.json
#239 update the DA region selection drop down
The list is entered in the existing order, by geography and then alphabetically.
```
/run pipeline
```
> fix: update DA region selection

- examples/complete/README.md
- examples/complete/main.tf
- examples/fscloud/main.tf
- solutions/standard/main.tf
- solutions/standard/version.tf
- tests/existing-resources/main.tf
Unblock renovate. The process appeared to go slightly wrong, were as it had been running fine in the past. Manually fix this time and if the problem occurs again dig deeper. 
This should unblock #249 and #254
```
/run pipeline
```
- Use …
> Unblock renovate

- tests/pr_test.go
> test: use hpcs-us-south for DA test

- solutions/standard/catalogValidationValues.json.template
us-east has been deleted. Need to move to us-south
```
/run pipeline
```
> fix: update catalog validation to use us-south HPCS

- modules/fscloud/main.tf
Address recent ci dependancies pipeline failure with 
```
Check: CKV_SECRET_6: "Base64 High Entropy String"
FAILED for resource: 70d6b2d4e09758837e2cd294b6fb07da6aefc14e
File: /modules/fscloud/main.tf:5-6
Guide: https://docs.prismacloud.io/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-6
5 |   secrets_manager_name              = var.secrets_manager_name #tfsec:ignore:genera**********	
```
```
/run pipeline
```
- Use a conventional commit message to set the release level. Follow the …
> fix: secret manager name is not high entropy string

- README.md
- examples/basic/version.tf
- examples/complete/README.md
- examples/complete/version.tf
- examples/fscloud/version.tf
- solutions/standard/version.tf
- tests/existing-resources/version.tf
- version.tf
> chore: bump provider version

- ibm_catalog.json
https://github.ibm.com/GoldenEye/issues/issues/14095
```
/run pipeline
```
> security enforced

- tests/existing-resources/outputs.tf
- tests/new-resources/main.tf
- tests/pr_test.go
Update existing resources for tests to reference current code rather than an old version of module.
```
/run pipeline
```
> fix: consume current version of module

- solutions/fully-configurable/main.tf
- solutions/fully-configurable/variables.tf
- solutions/security-enforced/variables.tf
This PR updates the resource group module to 1.3.0.
> chore: update 'resource_group version'= '1.3.0'

- solutions/fully-configurable/main.tf
> fix: fix the Event Notifications topic name in the DA
