terraform-ibm-modules/terraform-ibm-secrets-manager

tests/pr_test.go
Eu-es does not have the quota increase for SM instances. This is set in secmgr prefs file in common-dev-assets. Update test to pick up this file.
```
/run pipeline
```
=> test: get region from secmgr prefs 

README.md, examples/basic/outputs.tf, examples/basic/variables.tf, modules/fscloud/README.md, modules/fscloud/outputs.tf, outputs.tf, solutions/standard/outputs.tf
output secret manager region as an output.
outputted var as region is not included in attribute reference https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/resource_instance#attribute-reference.
https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/issues/83
Expose the sm region as an output.
```
/run pipeline
```
- Include information …
=> feat: output secret manager region

README.md, examples/basic/version.tf, examples/complete/README.md, examples/complete/main.tf, examples/complete/version.tf, examples/fscloud/version.tf, modules/fscloud/README.md, modules/fscloud/version.tf, solutions/standard/main.tf, version.tf
Bump IBM Provider to 1.62.0 (to support pending CBR upgrade in main module)
Bump key-protect-all-inclusive to kms-all-inclusive to be consistent across module (examples only)
Bump kms-all-inclusive to latest 3.8.5 version (solutions/standard DA)
Bump to IBM Provider 1.62.0.
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. …
=> fix: bump kms-all-inclusive and IBM provider

solutions/standard/main.tf, solutions/standard/version.tf
Fix issue with topics failing on initial apply and add sleep which depends on secrets manager module.
Fix issue with topics failing on initial apply and add sleep which depends on secrets manager module.
```
/run pipeline
```
- Use the …
=> fix: broken topic event notifications

README.md, examples/complete/main.tf, examples/fscloud/main.tf, main.tf, modules/fscloud/README.md, modules/fscloud/main.tf, modules/fscloud/outputs.tf, modules/fscloud/variables.tf, modules/secrets/README.md, modules/secrets/main.tf, modules/secrets/outputs.tf, modules/secrets/variables.tf, modules/secrets/version.tf, outputs.tf, tests/pr_test.go, variables.tf
Issue: https://github.ibm.com/GoldenEye/issues/issues/9825
```
/run pipeline
```
=> feat: add support for creating multiple secrets/secret_groups

solutions/standard/main.tf, solutions/standard/variables.tf, tests/pr_test.go
A flag is required to enable/disable event notifications on the DA (#176)
For the deployable architecture when passing an `existing_event_notification_instance_crn` it is necessary to set `enable_event_notification` to true.
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub …
=> fix: enable event notifications in secrets manager DA

solutions/standard/main.tf
Reduce the validation on the enable_event_notifications in the DA.
Permit an EN CRN to passed and enable_event_notification to be false.
This is to support the stacks use case, where an existing SM and EN are passed, allowing the enable_event_notifications flag to be true or false to control the creation (or not) of additional resources.
DA only validation updates to better support stacks use case.
```
/run pipeline
```
- Use a conventional commit message to set the release level. Follow the …
=> fix: for DA reduce validation on event notifications

main.tf
Add fix to prevent timing issue around KMS auth policy. This will address below intermittent issue:
- https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/issues/198
```
/run pipeline
```
- Use the **Squash and merge** …
=> fix: add fix to prevent timing issue around KMS auth policy

solutions/standard/outputs.tf
https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/issues/214
This PR fixes the resource group ID output in Secrets Manager Deployable Architecture.
```
/run pipeline
```
=> fix: Resource group output in DA

examples/complete/README.md, examples/complete/main.tf, solutions/standard/main.tf, tests/existing-resources/main.tf
Update KMS all inclusive which removes key ring force delete because it is deprecated by the provider
```
/run pipeline
```
=> fix(deps): bump KMS with code change

README.md, examples/basic/version.tf, examples/complete/README.md, examples/complete/version.tf, examples/fscloud/main.tf, examples/fscloud/version.tf, main.tf, version.tf
Update terraform terraform-ibm-modules/cbr/ibm to v1.28.1
Update required provider version to >= 1.70.0 to pick up the fix for this provider issue: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5590
Update terraform terraform-ibm-modules/cbr/ibm to v1.28.1
Update required provider version to >= 1.70.0 to pick up the fix for this provider issue: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5590
```
/run pipeline
```
- Use a conventional commit message to set the release level. Follow the …
=> fix(deps): bump CBR and IBM provider

main.tf
Prevented time_sleep resource creation when SM CRN is passed as input.
[Git Issue](https://github.ibm.com/GoldenEye/issues/issues/11543)
Prevents time_sleep resource creation when SM CRN is passed as input.
```
/run pipeline
```
- Use the …
=> fix:Prevented time_sleep resource creation when SM CRN is passed as input

ibm_catalog.json
- mark `existing_kms_instance_crn` required in catalog. By passing in a KMS instance, the DA will create a new key by default. Approach is consistent with other DAs
```
/run pipeline
```
=> fix: mark `existing_kms_instance_crn` required in catalog

cra-config.yaml, ibm_catalog.json, solutions/standard/provider.tf, solutions/standard/variables.tf, tests/pr_test.go
exposed [visibility](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs#visibility) value for the provider in the DA , with default value set to "private"
[Git issue](https://github.ibm.com/GoldenEye/issues/issues/11333)
exposes visibility value for the provider in the DA
```
/run pipeline
```
- Include information that users need to know about the PR in the …
=> feat:exposed visibility value for the provider in the DA

examples/complete/README.md, examples/complete/main.tf, examples/complete/version.tf, tests/other_test.go, tests/pr_test.go
We cannot migrate the us-east hpcs to use the VPC crypto units, we will have to delete the instance. Hence, using the us-south hpcs to run the tests.
```
/run pipeline
```
=> test: change the `existing_kms_instance_guid` to use us-south hpcs and add auth policy for service credential

tests/existing-resources/main.tf
When DA endpoints were all switched to private-only, the EN instance for tests was still public-only.
```
/run pipeline
```
=> test: privatize en instance

tests/pr_test.go
Add upgrade test for the DA
Issue: https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/issues/302
```
/run pipeline
```
=> test: add DA upgrade test

examples/complete/README.md, examples/complete/variables.tf, examples/fscloud/variables.tf, tests/other_test.go, tests/pr_test.go
Move any tests using KMS to au-syd.
issue: https://github.ibm.com/GoldenEye/issues/issues/12725
```
/run pipeline
```
=> move kms tests off EU

solutions/fully-configurable/catalogValidationValues.json.template, solutions/security-enforced/catalogValidationValues.json.template
Validation pipeline failing with:
`Error: [ERROR] Error creating access group: An access group with the name general-secrets-group-access-group already exists. Enter a different name.`
There is no easy way currently to use unique value in catalog pipeline, so disabling group creation for now
```
/run pipeline
```
- Include information that users need to know about the PR in the …
=> ci: disable `secret_groups` in DA validation to avid name clash

README.md, examples/basic/version.tf, examples/complete/README.md, examples/complete/version.tf, examples/fscloud/version.tf, modules/fscloud/README.md, modules/fscloud/version.tf, modules/secrets/README.md, modules/secrets/version.tf, solutions/fully-configurable/README.md, solutions/fully-configurable/version.tf, tests/existing-resources/version.tf, tests/new-resources/version.tf, tests/new-rg/version.tf, version.tf
Pull in the fix for https://github.com/IBM-Cloud/terraform-provider-ibm/issues/6269
```
/run pipeline
```
=> fix(deps): bump IBM provider to 1.79.0
